### ISSUE TITLE
Line Spacing 

### ISSUE THREAD

**Issue by emsipop** [emsipop/voting-calculator#11]
There's a lack of line spacing throughout the code when it's run, would be good to include some format editing to make the program look more visually appealing and easier to understand.

**Comment by emsipop** [comment]
Please commit any changes to the 'spacing' branch!

**Comment by Bluegigsolution8** [comment]
Unable to clear command line with C#.

**Comment by emsipop** [comment]
Let's just add in an extra space before the results are displayed! Using '\n'!

**Comment by Bluegigsolution8** [comment]
I have created the space before the results. :)
