### ISSUE TITLE
Incorrect Percentage Rounding

### ISSUE THREAD

**Issue by emsipop** [emsipop/voting-calculator#4]
Having a problem getting the percentage result to come out exactly like the online calculator, the result tends to vary by 0.03%. Tried Math.Round to 2 dp, which is as close as I can get. If anybody could get closer to the answer that would be great! Thanks! :)

**Comment by jman9003** [comment]
The problem that we had was the original calculator that was provided to us had faults to begin with.

**Comment by Bluegigsolution8** [comment]
On it! Will account for the 0.03 difference in the total

**Comment by Bluegigsolution8** [comment]
if (percYes < 0.00)
            {
                percYes = 0.00;
            }

            if (percNo > 100.00)
            {
                percNo = 100.00;
            }

            if (percAb > 100.00)
            {
                percAb = 100.00;
            }

**Comment by emsipop** [comment]
that looks great!
