### ISSUE TITLE
Problem new objects

### ISSUE THREAD

**Issue by emsipop** [emsipop/voting-calculator#7]
Class fully implemented and used within the main class. Problem with creating new object for each instance of the class.

_Originally posted by @emsipop in https://github.com/emsipop/voting-calculator/pull/6#issuecomment-588305596_

**Comment by emsipop** [comment]
The country-class branch program runs with no errors, however when giving the option to remove countries from voting, those removed countries don't remain as a new object instantiation is required when it comes to changing the votes! Maybe we could save the countries class object as a new variable in the main method and just use the copy instead of the main class, what do you think? :)

**Comment by Bluegigsolution8** [comment]
Unless... you edit the countries participating within the same class! That way the object will be instantiated from the final edited country dictionary! :)

**Comment by emsipop** [comment]
Thanks for the help. Struggling to get that to work, I'm going to delete Country as a class and include it as a method within the main program. Will implement classes of each rule instead!
